# Generated by Django 5.1 on 2024-08-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.BigIntegerField()),
                ('chat_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('thread_id', models.BigIntegerField(default=0)),
                ('business_connection_id', models.CharField(blank=True, max_length=255)),
                ('destiny', models.TextField(max_length=255)),
                ('state', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['bot_id', 'chat_id', 'user_id', 'thread_id', 'business_connection_id', 'destiny'], name='aiogram_djp_bot_id_6bcf05_idx')],
                'unique_together': {('bot_id', 'chat_id', 'user_id', 'thread_id', 'business_connection_id', 'destiny')},
            },
        ),
    ]
