# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]

env:
  USING_POETRY_VERSION: ">=1.1.7"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install poetry${USING_POETRY_VERSION}
        poetry install -v
    - run: poetry check
    - run: poetry run black python_telegram_bot_django_persistence --check

  publish:
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
    - uses: actions/checkout@v2
    - name: Set up latest stable Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install poetry${USING_POETRY_VERSION}
        poetry install --no-dev -v
    - name: Build package
      run: |
        poetry version $(git describe --tags)
        poetry build
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags/')
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
      run: poetry publish -v
